blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_function, name='search_url'),
    path('news/<slug:slug>/', views.post_detail, name='post_detail_url'),
    path('categories/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('register/', views.register, name = 'register'),
]

umbrella/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField('Sarlavha', max_length=255)
    slug = models.SlugField('Silka', unique=True)
    image = models.ImageField('Rasm', blank=True, null=True)
    
    
    class Meta:
        verbose_name = 'Kategotiya'
        verbose_name_plural = 'Kategoriyalar'
    
    def get_absolute_url(self):
        return reverse("category_detail_url", kwargs={'slug':self.slug})

    def __str__(self):    
        return self.title__icontains
        
class Image(models.Model):
    image = models.ImageField('Picture', upload_to='images/')
    title = models.CharField('Title',max_length=255)

    class Meta:
        verbose_name = "picture"
        verbose_name_plural = "pictures"

    
    def __str__(self):
        return self.title

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name = "Author", null=True)
    title = models.CharField("Sarlovha", max_length=255)
    slug = models.SlugField("Silka", unique=True)
    image = models.ImageField("Rasm", blank=True, null=True)
    video = models.FileField('Video', upload_to='videos/', null=True)
    content = models.TextField("Text")
    date = models.DateTimeField('Sana', default=timezone.now)
    publish = models.BooleanField("Taqdim etish", default=False)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Category', related_name='posts')

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Postlar'
        
    def __str__(self):
       return self.title
       
    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug':self.slug})

    def __str__(self):    
        return self.title

class View(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Avtor")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Yangilik")
    text = models.TextField("Kommentariya", null=True)
    data = models.DateTimeField("Sana", default=timezone.now)


    class Meta:
        verbose_name = "Coment"
        verbose_name_plural ="Coments"

    def __str__(self):   
        return self.user.username        
 

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms 
from django.contrib.auth.models import User



class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Parol", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Takroran", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label="Email", required=True, widget=forms.EmailInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label="Ism", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label="Familiya", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))


    class Meta:
        model = User
        fields = ("first_name","last_name", "username", "email", "password1", "password2")
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.last_name = self.cleaned_data["last_name"]
        user.first_name = self.cleaned_data["first_name"]

        if commit:
            user.save()
            return user  

blog/views.py
from django.shortcuts import render, redirect, reverse
from .models import Post, Category
from django.db.models import Q
from django.http import request
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout


def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html',{'posts':posts})

def search_function(request):
    query = request.GET.get('search_input')
    posts = Post.objects.filter(Q(title__icontains = query))
    return render(request, 'blog/search.html',{'query': query, 'posts': posts})

def post_detail(request, slug):   
    post = Post.objects.get(slug__exact = slug)
   
    return render(request, 'blog/post_detail.html',{'post':post})

def category_detail(request, slug):
    category = Category.objects.get(slug__exact = slug)
    return render(request, "blog/category_detail.html", {'category': category})

def register(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('index')
        else:
            form = RegisterForm()
        return render(request, 'blog/register.html', {'form':form})   
    return redirect('index') 

def comment(request, slug):
    post = Post.objects.get(slug__exact = slug)
    if request.method == "POST":
        post.comment_set.create(
           user = request.user,
           text = request.POST.get('text')
        )     
        return redirect(reverse('post_detail_url',kwargs={'slug': post.slug}))
    return redirect(reverse('post_detail_url',kwargs={'slug': post.slug}))           

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">UMBRELLA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Top views</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
            {% if not user.is_authenticated %}
          </li>
          <li class="nav-item">
             <a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Registration</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Enter</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Exit</a>
            </li>
            {% endif %}
           
          </ul>
          <form action="{% url 'search_url' %}" method='GET' class="d-flex">
            <input name="search_input" required class="form-control me-2" type="search" placeholder="Searching..." aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    
  
    
    {% block content %}

    {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
<script src="/static/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/65030ee4a8.js" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.category.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">

            <h3 class="text-center">{{post.category.title}}</h3>
            {% if post.image.url != null %}
                <img src="{{category.image.url}}" style="width: 100%;" alt="">
            {% endif %}
           <h3>{{category.title}}</h3>
            <hr>
            <div class="row">
                {% for post in category.post_set.all %}
                <div class="col-md-4">
                  <div class="card">
                      <img src="{{post.image.url}}" class="card-img-top" alt="...">
                    
                      <div class="card-body">
                        <a href="{{post.get_absolute_url}}">
                        <h5 class="card-title">{{post.title}}</h5></a>
                        <p class="card-text">{{post.content|slice:"0:100"}}</p>
                        <a href="{{post.category.get_absolute_url}}" class="btn btn-primary">{{post.category.title}}</a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
            </div>
                
            </p>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<header>
  <div id="home icons" class="my-5 text-center"></div>
    <div class="container" >
      <div class="row" style="margin-top: 30px;">
        <div class="col-md-4">
          <i class="fas fa-cog fa-3x"></i>
           <h3>Turning Gears</h3>
           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sapiente dicta nulla molestiae vel, consequatur tempore necessitatibus temporibus repudiandae aliquid fugit repellat harum. Cumque minima beatae velit aspernatur a omnis?</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-cloud fa-3x"></i>
          <h3>Sending Data</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat molestias quae nostrum consectetur quia culpa, ad nobis suscipit numquam, rerum, asperiores earum. Quam non cupiditate amet eum praesentium animi ullam!</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-cart-plus fa-3x"></i>
          <h3>Making Money</h3>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, eveniet amet natus molestiae perferendis labore quae reprehenderit incidunt laboriosam modi consequatur similique dolorem alias. Porro aperiam velit voluptatum ipsum expedita.</p>
        </div>
      </div>
    </div></header>
  </div>
  <section>
    <div class="container-xxl">
  <div class="row align-items-center">
    {% for post in posts %}
    <div class="col-7"><h1>Welcome to our Group</h1></div>
    <div class="col-5"><img class="w-100" src="https://images.pexels.com/photos/5641953/pexels-photo-5641953.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt=""></div>
  </div>
</div>
   </section>
   <section> 
    <div class="container-xxl">
  <h2>First informational</h2>
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="row">
          <div class="col">
            <div class="card" style="width: 18rem;">
              {% if post.image.url != null %}
              <video src="https://ak.picdn.net/shutterstock/videos/30559417/preview/stock-footage-drag-racing-car-burns-rubber-off-its-tires-in-preparation-for-the-race.webm" autoplay muted loop ></video>
              {% endif %}
              <div class="card-body">
               <a href="{{post.get_absolute_url}}">{{post.title}}></a> 
                <p class="card-text">{{post.content|slice:"0:100"}}</p>
                <a href="{{post.category.get_absolute_url}}">{{post.title}} class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1023624340/preview/stock-footage-beautiful-sunrise-over-the-earth-view-from-space-satellite-cities-at-night-changing-from-night.mp4" autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1069499368/preview/stock-footage-burnaby-vancouver-british-columbia-canada-time-lapse-beautiful-panoramic-aerial-view-of-a.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1031822039/preview/stock-footage-beautiful-top-view-time-lapse-of-car-traffic-at-roundabout-lane-and-buildings-k-drone-aerial-zoom.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="row">
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1027882880/preview/stock-footage-young-entrepreneur-walkling-toward-city-sky-scrapers-dubai-urban-panorama-futuristic-digital-nomad.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1033854800/preview/stock-footage-portrait-serious-face-african-american-man-ooking-at-camera-enjoying-in-urban-city-handsome.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1045628542/preview/stock-footage-digitalization-concept-human-finger-turns-on-touch-screen-button-and-activates-futuristic.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
           <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1038801227/preview/stock-footage-high-angle-shot-of-a-crowded-pedestrian-crossing-in-big-city-augmented-reality-of-social-media.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          
        </div>
      </div>
      <div class="carousel-item">
        <div class="row">
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1049073496/preview/stock-footage-group-using-video-conferencing-technology-in-office-for-video-call-with-colleagues-abroad.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1008551917/preview/stock-footage-stylish-office-in-loft-style-businessman-makes-notes-on-the-wall-business-idea-thinking-design.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/1038291482/preview/stock-footage-airplane-flies-over-business-skyscrapers-against-sunset-clouds-beautiful-d-animation-k-ultra-hd.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card" style="width: 18rem;">
              <video src="https://ak.picdn.net/shutterstock/videos/32229790/preview/stock-footage-family-toasting-wine-at-christmas-dinner-family-enjoying-christmas-dinner-together-at-home-with.mp4"autoplay muted loop></video>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
   </section>
   <footer style=" background-color: #212529;">
     <div class="container">
       <div class="row padding text-center">
         <div class="col-12" style="color:white">
           <h2>Our contacts</h2>
         </div>
         <div class="col-12 social padding" style="font-size: 4em; padding: 15px;">
           <a href=""><i class="fab fa-twitter" style="color: #00aced;"></i></a>
           <a href=""><i class="fab fa-instagram" style="color: #517fa4;"></i></a>
           <a href=""><i class="fab fa-youtube" style="color: #bb0000;"></i></a>
           <a href=""><i class="fab fa-facebook" style="color: #3b5998;"></i></a>
           <a href=""><i class="fab fa-google-plus-g" style="color: ##dd4b39;"></i></a>
         </div>
       </div>
     </div>
     

   </footer>
  
{% endfor %}

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h3 class="text-center">{{post.title}}</h3>
            {% if post.image.url != null %}
                <img src="{{post.image.url}}" style="width: 100%;" alt="">
            {% endif %}
            <p>{{post.content}}</p>
            <p class="text-left">
                <i>Prosmotri: {{post.views}}</i>
                <i>{{post.date|date:"d F,Y"}}</i>
            </p>
            <hr>
            <p><i>Kommentariyalar: {{post.comment_set.count}}</i></p>
            <h3>Kommentariya qoldirish</h3>
            {% if user.is_authenticated %}
            <form action="{% url 'comment' post.slug %}" method="POST">
                {% csrf_token %}
                <p>
                    <textarea name="text" id="" cols="30" rows="10" class="form-control"></textarea>
                </p>
                <p class="text-right">
                    <button class="btn btn-outline-primary">Yuborish</button>

                </p>
            </form> 
            {% else %}
            <p>Kommentariya qoldirish uchun <a href="{% url 'register'%}">Registratsiya qiling yoki <a href="{% url 'login' %}"></a> </a></p>
            {% endif %}
            <hr>
            {% for comment in post.comment_set.all %}
            <div class="col-md-12">
                <h3>{{comment.user.username}}</h3>
                <p>{{comment.text}}</p>
                <p class="text-right">{{comment.data|timesince}} oldin</p>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block title %}
Registratsiya
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
           <form action="{% url 'register' %}" method="POST">
               {% csrf_token %}
               {{form.as_p}}
               <button class="btn btn-success">Registratsiya</button>
           </form>
            {% if post.image.url != null %}
                <img src="{{register.image.url}}" style="width: 100%;" alt="">
            {% endif %}
            <p>{{register.content}}</p>
            
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}
{% block title %}
qidiruv bo'yicha {{query}} 
{% endblock %}

{% block content %}
<div class="container">
     <div class="row">
         <div class="col-md-9">
             <div class="row">
                  {% for post in posts %}
                  <div class="col-md-4">
                      {% if post.image.url != null %}
                      <img src="{{post.image.url}}" alt="" >
                    {% endif %}
                    <h3 class="text-center">{{podt.title}}</h3>
                  </div>
                  {% empty %}
                  <h2>Suralgan '{{query}}' bo'yicha hech narsa topilmadi </h2>
                  
                  {% endfor %}
             </div>

         </div>
     </div>
</div>



{% endblock %}